name: Run Telegram Bot Daily

on:
  schedule:
    - cron: "29 11 * * *"   # Запуск перед публикацией в 15:00 (+3 по МСК)
    - cron: "30 11 * * *"   # Запуск перед публикацией в 15:00 (+3 по МСК)
    - cron: "55 18 * * *"  # Запуск перед публикацией в 22:00 (+3 по МСК)
  workflow_dispatch:  

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python daily_diary_bot.py
